### ISSUE TITLE
你好，请问README.md中的这句话是什么意思？

### ISSUE THREAD

**Issue by woshoxxx** [talting/FBHomePage#1]
`
6、没经过同意就弄走的你是什么牛马？
`
我看到本仓库采用的是Apache 2.0许可证
根据该许可证第2条：
Grant of Copyright License. Subject to the terms and conditions of
      this License, each Contributor hereby grants to You a perpetual,
      worldwide, non-exclusive, no-charge, royalty-free, irrevocable
      copyright license to reproduce, prepare Derivative Works of,
      publicly display, publicly perform, sublicense, and distribute the
      Work and such Derivative Works in Source or Object form.
**在遵守本许可的条款和条件的前提下，每位投稿人特此授予您永久的，全球性的，非独家的，免费的，免版税的，不可撤销的版权许可，以复制，准备衍生作品，公开展示，公开演出，从属许可证，并以源或对象形式分发工作和此类衍生作品。**
该许可证允许复制，准备衍生作品。
而README.md中的这句话与其矛盾，请问应该以什么为准？

**Comment by talting** [comment]
删了已经
